name: vehicle_plate_scanner
description: A package to scan images for brazilian vehicle plates.
version: 0.1.0
homepage: https://github.com/marcosfons/vehicle_plate_scanner

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^4.2.0

  camera: ^0.11.0+1

  google_mlkit_commons: ^0.7.1
  google_mlkit_text_recognition: ^0.13.0

  logger: 

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter: